# fly.toml app configuration file generated for arthurg on 2023-06-11T10:51:16+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "arthurg"
primary_region = "arn"

[env]
  PORT = "8080" # add this

[http_service]
  processes = ["app"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0


